# Valores Ausentes (Missing Values)

Nesta seção aprenderemos como identificar e tratar valores ausentes utilizando o Pandas.

In [1]:
import pandas as pd
import numpy as np

dados = {
    "Nome": ["Ana", "Bruno", "Carlos", "Daniela", "Eduardo"],
    "Idade": [23, None, 35, 29, None],
    "Cidade": ["Blumenau", None, "Pomerode", "Indaial", "Gaspar"]
}

df = pd.DataFrame(dados)

df

      Nome  Idade    Cidade
0      Ana   23.0  Blumenau
1    Bruno    NaN       NaN
2   Carlos   35.0  Pomerode
3  Daniela   29.0   Indaial
4  Eduardo    NaN    Gaspar

## isna()

A função `isna()` verifica cada posição da tabela e retorna:

- **True** → existe um valor ausente (`NaN`)
- **False** → existe um valor preenchido

Essa função é útil para localizar onde estão os dados faltantes.

In [2]:
df.isna()

    Nome  Idade  Cidade
0  False  False   False
1  False   True    True
2  False  False   False
3  False  False   False
4  False   True   False

### Contando valores ausentes

Normalmente não queremos visualizar toda a tabela de `True` e `False`.

Podemos contar quantos valores ausentes existem em cada coluna utilizando:

`isna().sum()`

In [3]:
df.isna().sum()

Nome      0
Idade     2
Cidade    1
dtype: int64

### Visualizando apenas as linhas com idade ausente

Também podemos localizar somente os registros que possuem valores ausentes em uma coluna específica.

In [4]:
df[df["Idade"].isna()]

      Nome  Idade  Cidade
1    Bruno    NaN     NaN
4  Eduardo    NaN  Gaspar

### notna()

A função `notna()` faz exatamente o contrário de `isna()`.

- True → possui valor
- False → está ausente

In [5]:
df[df["Cidade"].notna()]
#df[df["Cidade"].notna() & df["Idade"].notna()]

      Nome  Idade    Cidade
0      Ana   23.0  Blumenau
2   Carlos   35.0  Pomerode
3  Daniela   29.0   Indaial
4  Eduardo    NaN    Gaspar

## Exercício

Mostre apenas os registros onde a coluna **Cidade** está vazia.

In [9]:
df[df["Cidade"].isna()]

    Nome  Idade Cidade
1  Bruno    NaN    NaN

## dropna()

A função `dropna()` remove valores ausentes.

Mas existem várias formas de utilizá-la.

### 1) Sem parâmetros

Remove qualquer linha que possua pelo menos um valor ausente.
Quando usar? Quando todas as colunas são obrigatórias.

In [ ]:
df.dropna()

### 2) Removendo apenas linhas sem idade

Nem sempre queremos remover todas as linhas.

Podemos indicar quais colunas serão verificadas utilizando `subset`.
Somente linhas onde Idade é NaN serão removidas.

In [ ]:
df.dropna(subset=["Idade"])

### 3) Verificando mais de uma coluna

Também podemos exigir que determinadas colunas estejam preenchidas.
Remove linhas que possuem valores ausentes em Idade ou Cidade.

In [ ]:
df.dropna(subset=["Idade", "Cidade"])

### 4) Linhas completamente vazias

Quando importamos um Excel é comum existirem linhas totalmente vazias.

In [ ]:
df.dropna(how="all")

### 5) Removendo colunas

Também é possível remover colunas que possuem valores ausentes.

axis=0 → trabalha com linhas (padrão)

axis=1 → trabalha com colunas

Na prática, remover colunas inteiras é pouco comum. Geralmente preferimos preencher os valores ausentes.

In [ ]:
df.dropna(axis=1)

## fillna()

Ao invés de remover registros, podemos preencher os valores ausentes.

In [ ]:
df.fillna("Não informado")

### Preenchendo apenas uma coluna

In [ ]:
df["Cidade"] = df["Cidade"].fillna("Não informado")

### Utilizando a média
Idade é um valor numérico.
Uma estratégia comum é utilizar a média.

In [ ]:
media = df["Idade"].mean()

df["Idade"] = df["Idade"].fillna(media)

# Duplicatas

Durante a coleta de dados, é comum que um mesmo registro seja inserido mais de uma vez.

Esses registros repetidos são chamados de **duplicatas**.

Antes de removê-las, devemos identificar se realmente representam um erro ou se fazem parte do processo de negócio.

In [ ]:
dados = {
    "Nome": [
        "Ana",
        "Bruno",
        "Carlos",
        "Ana",
        "Eduardo",
        "Carlos"
    ],
    "Cidade": [
        "Blumenau",
        "Pomerode",
        "Gaspar",
        "Blumenau",
        "Indaial",
        "Gaspar"
    ],
    "Idade": [
        25,
        30,
        40,
        25,
        35,
        40
    ]
}

df = pd.DataFrame(dados)

df

## duplicated()

A função `duplicated()` verifica quais linhas estão duplicadas.

Ela retorna:

- **False** → primeira ocorrência.
- **True** → registros repetidos.

In [ ]:
df.duplicated()

## Visualizando apenas as duplicatas

Podemos utilizar o resultado do `duplicated()` como filtro.

In [ ]:
df[df.duplicated()]

## Contando duplicatas

Para descobrir quantos registros duplicados existem:

In [ ]:
df.duplicated().sum()

## duplicated(keep="first")
Por padrão (`keep="first"`), a primeira ocorrência é mantida e as demais são marcadas como duplicadas.

In [ ]:
df.duplicated(keep="first")

Mantém a última ocorrência e marca as anteriores como duplicadas.

In [ ]:
df.duplicated(keep="last")

## drop_duplicates()

Remove registros duplicados do DataFrame.

Por padrão, mantém a primeira ocorrência.

In [ ]:
df.drop_duplicates()

### Mantendo a última ocorrência

In [ ]:
df.drop_duplicates(keep="last")

### Removendo duplicatas considerando apenas uma coluna

Nem sempre precisamos comparar todas as colunas.

Podemos verificar duplicatas utilizando apenas uma ou mais colunas específicas.

In [ ]:
df.drop_duplicates(subset=["Nome"])

### Quando utilizar?

✔ Quando um cadastro foi importado duas vezes.

✔ Quando um cliente aparece repetido por erro.

✔ Quando registros idênticos foram inseridos acidentalmente.

⚠ Nem toda duplicata deve ser removida.

Exemplo:

Um cliente pode realizar duas compras iguais no mesmo dia.

Nesse caso, os registros são parecidos, mas representam duas vendas diferentes.

### Exercício

1. Conte quantos registros duplicados existem.

2. Mostre apenas as duplicatas.

3. Remova as duplicatas mantendo a primeira ocorrência.

4. Remova duplicatas considerando apenas a coluna **Nome**.

In [10]:
import pandas as pd

produtos = pd.DataFrame({
    "Pedido": [101, 102, 103, 104, 105, 106, 107, 108],
    "Cliente": [
        "Marcos",
        "Juliana",
        "Pedro",
        "Marcos",
        "Amanda",
        "Juliana",
        "Carlos",
        "Pedro"
    ],
    "Produto": [
        "Notebook",
        "Mouse",
        "Monitor",
        "Notebook",
        "Teclado",
        "Mouse",
        "Notebook",
        "Cadeira"
    ],
    "Quantidade": [1, 2, 1, 1, 1, 2, 1, 1]
})

print(produtos)

   Pedido  Cliente   Produto  Quantidade
0     101   Marcos  Notebook           1
1     102  Juliana     Mouse           2
2     103    Pedro   Monitor           1
3     104   Marcos  Notebook           1
4     105   Amanda   Teclado           1
5     106  Juliana     Mouse           2
6     107   Carlos  Notebook           1
7     108    Pedro   Cadeira           1

In [16]:
# 1. Conte quantos registros duplicados existem.
print(produtos.duplicated(subset=["Cliente","Produto","Quantidade"]).sum())

2

In [ ]:
# 2. Mostre apenas as duplicatas.

produtos[produtos.duplicated(subset=["Cliente","Produto", "Quantidade"])]

   Pedido  Cliente   Produto  Quantidade
3     104   Marcos  Notebook           1
5     106  Juliana     Mouse           2

In [ ]:
# 3. Remova as duplicatas mantendo a primeira ocorrência.

print(produtos.drop_duplicates(subset=["Cliente", "Produto", "Quantidade"]))

   Pedido  Cliente   Produto  Quantidade
0     101   Marcos  Notebook           1
1     102  Juliana     Mouse           2
2     103    Pedro   Monitor           1
3     104   Marcos  Notebook           1
4     105   Amanda   Teclado           1
5     106  Juliana     Mouse           2
6     107   Carlos  Notebook           1
7     108    Pedro   Cadeira           1

In [ ]:
# 4. Remova duplicatas considerando apenas a coluna **Nome**.
produtos.drop_duplicates(subset=["Nome"])

# Outliers

Outliers são valores muito diferentes da maioria dos dados.

Eles podem representar:

- erro de digitação;
- erro de coleta;
- ou um valor verdadeiro.

Por isso, **nem todo outlier deve ser removido**.

### Exemplo 1 - Idade

In [ ]:
dados = {
    "Idade": [
        18,
        20,
        22,
        25,
        27,
        30,
        150
    ]
}

df = pd.DataFrame(dados)

df

Nesse exemplo, a idade **150 anos** provavelmente é um erro de cadastro.

Esse registro deve ser investigado.

### Exemplo 2 — Vendas

In [ ]:
dados = {
    "Venda": [
        250,
        300,
        280,
        320,
        350,
        280,
        18000
    ]
}

df = pd.DataFrame(dados)

df

O valor **18000** parece um outlier.

Mas será que é um erro?

Talvez não.

Pode representar uma compra corporativa ou um cliente muito importante.

Antes de remover um outlier, sempre verifique o contexto.

## Detectando Outliers com IQR

Uma forma bastante utilizada para detectar outliers é o método **IQR (Intervalo Interquartil)**.

Os passos são:

1. Calcular Q1.
2. Calcular Q3.
3. Calcular o IQR.
4. Definir os limites inferior e superior.
5. Filtrar os valores fora desses limites.

In [ ]:
dados = {
    "Idade":[18,20,22,25,27,30,150]
}

df = pd.DataFrame(dados)

18 20 22 25 27 30 150
       |
       Q1

18 20 22 25 27 30 150
             |
             Q3

In [ ]:
Q1 = df["Idade"].quantile(0.25)

Q3 = df["Idade"].quantile(0.75)

IQR = Q3 - Q1

print(Q1)
print(Q3)
print(IQR) # distancia entre Q1 e Q3

In [ ]:
limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR

print(limite_inferior)
print(limite_superior)

O 1.5 é um fator estatístico definido pelo método do IQR para criar uma margem de segurança ao redor dos dados considerados normais.

In [ ]:
outliers = df[
    (df["Idade"] < limite_inferior) |
    (df["Idade"] > limite_superior)
]

outliers

## Removendo Outliers

Após identificar os outliers, podemos removê-los.

In [ ]:
df = df[
    (df["Idade"] >= limite_inferior) &
    (df["Idade"] <= limite_superior)
]

df

# Ou substituir valor
#df["Idade"] = df["Idade"].replace(150, 50)

### Quando remover?

✔ Erros de digitação.

✔ Valores impossíveis.

✔ Dados claramente incorretos.

### Quando manter?

✔ Compras corporativas.

✔ Salário do diretor.

✔ Grandes clientes.

✔ Eventos raros, mas reais.

# Normalização

Normalizar significa padronizar a forma como os dados estão armazenados.

Isso evita problemas durante filtros, agrupamentos e análises.

In [ ]:
dados = {
    "Cidade":[
        "Blumenau",
        " blumenau ",
        "BLUMENAU",
        "Blumenau ",
        "Pomerode",
        "POMERODE"
    ]
}

df = pd.DataFrame(dados)

df

## strip()
Remove espaços no início e no final do texto.

In [ ]:
df["Cidade"] = df["Cidade"].str.strip()

df

## lower()
Converte todos os caracteres para minúsculo.

In [ ]:
df["Cidade"] = df["Cidade"].str.lower()

df

## upper() 
Converte todos os caracteres para maiúsculo.

In [ ]:
df["Cidade"] = df["Cidade"].str.upper()

df

## title()
Deixa a primeira letra de cada palavra em maiúsculo.

In [ ]:
df["Cidade"] = df["Cidade"].str.title()

df

## replace()
Substitui um texto por outro.

In [ ]:
dados = {
    "Cidade":[
        "BNU",
        "Pomerode",
        "BNU",
        "Gaspar"
    ]
}

df = pd.DataFrame(dados)

In [ ]:
df["Cidade"] = df["Cidade"].replace(
    "BNU",
    "Blumenau"
)

df

## Conversão de tipos
Algumas colunas numéricas podem ser importadas como texto.

Podemos convertê-las utilizando `to_numeric()`.

In [ ]:
dados = {
    "Idade":[
        "20",
        "35",
        "abc",
        "40"
    ]
}

df = pd.DataFrame(dados)

In [ ]:
df["Idade"] = pd.to_numeric(
    df["Idade"],
    errors="coerce" # elimina texto
)

df

## Padronização de datas

In [ ]:
dados = {
    "Data":[
        "01/02/2025",
        "15/03/2025",
        "20/04/2025"
    ]
}

df = pd.DataFrame(dados)

df

In [ ]:
df.dtypes

In [ ]:
df["Data"] = pd.to_datetime(
    df["Data"],
    dayfirst=True # Devido padrão de datas brasileiro 15/01/2026 (Formato no texto: DD/MM/AAAA ou DD-MM-AAAA)
)

# Se as datas já estiverem no padrão internacional ISO (AAAA-MM-DD, como 2026-04-05) não precisa usar dayfirst.

df

Após a conversão, a coluna passa a ser do tipo **datetime**, permitindo realizar filtros por datas, extrair mês, ano, dia da semana e outras operações.

In [ ]:
# Extrair o ano
print(df["Data"].dt.year)

# Extrair o mês
print(df["Data"].dt.month)

# Extrair o dia
print(df["Data"].dt.day)

# Extrair o nome do dia da semana
print(df["Data"].dt.day_name())

In [ ]:
# Criar novas colunas no DF
df["Ano"] = df["Data"].dt.year
df["Mes"] = df["Data"].dt.month
df["Dia"] = df["Data"].dt.day
df["Dia_Semana"] = df["Data"].dt.day_name()

print(df)

# Exemplo Completo - Limpeza de Dados

## Projeto: Limpeza de Cadastro de Clientes

Uma empresa recebeu uma base de clientes exportada de vários sistemas.

Antes de criar relatórios, precisamos verificar:

- Valores ausentes
- Clientes duplicados
- Idades incorretas
- Valores extremos
- Cidades com formatos diferentes
- Tipos de dados incorretos

Nossa missão será preparar essa base para análise.

In [ ]:
dados = {
    "ID_Cliente": [
        1,2,3,4,5,6,7,8,9,10
    ],

    "Nome": [
        "Ana",
        "Bruno",
        "Carlos",
        "Daniela",
        "Eduardo",
        "Fernanda",
        "Gabriel",
        "Helena",
        "Ana",
        "João"
    ],

    "Idade": [
        25,
        None,
        35,
        29,
        150,
        42,
        -5,
        31,
        25,
        None
    ],

    "Cidade": [
        "Blumenau",
        " BLUMENAU ",
        "blumenau",
        "Pomerode",
        "POMERODE",
        None,
        "Gaspar",
        "gaspar ",
        "Blumenau",
        None
    ],

    "CPF": [
        "11111111111",
        None,
        "22222222222",
        "33333333333",
        "44444444444",
        "55555555555",
        None,
        "77777777777",
        "11111111111",
        "88888888888"
    ],

    "Venda_Total": [
        1500,
        2300,
        1800,
        None,
        25000,
        3200,
        900,
        2100,
        1500,
        2700
    ]
}


df = pd.DataFrame(dados)

df

Antes de alterar qualquer informação, precisamos entender a estrutura dos dados.

In [ ]:
df.info()

In [ ]:
df.describe()

## Valores ausentes

In [ ]:
df.isna().sum()

### Visualizando clientes sem idade

In [ ]:
df[df["Idade"].isna()]

### Decisão de negócio

Agora precisamos decidir:

#### Idade

Não podemos excluir todos os clientes sem idade.

Podemos preencher utilizando a média.

#### Cidade

Podemos usar "Não informado".

#### CPF

Não devemos inventar um CPF.

Mantemos vazio.

#### Venda

Depende da regra.

Se ausência significa que não houve venda, podemos utilizar 0.

In [ ]:
# Idade com média
media_idade = df["Idade"].mean()

df["Idade"] = df["Idade"].fillna(media_idade)

In [ ]:
# Cidade
df["Cidade"] = df["Cidade"].fillna(
    "Não informado"
)

In [ ]:
# Venda
df["Venda_Total"] = df["Venda_Total"].fillna(0)

In [ ]:
# Conferindo
df.isna().sum()

## Duplicatas

Agora vamos verificar se existem clientes repetidos.

O cliente Ana aparece duas vezes.

Precisamos verificar se realmente é duplicação.

In [ ]:
# Identificando
df.duplicated()

In [ ]:
# Visualizando 
df[df.duplicated()]

In [ ]:
# Contando
df.duplicated().sum()

In [ ]:
# Removendo 
df = df.drop_duplicates()

### Duplicatas considerando apenas CPF
Em muitos sistemas, o CPF é o identificador único.

Nesse caso podemos verificar duplicatas apenas pelo CPF.

In [ ]:
df.drop_duplicates(
    subset=["CPF"]
)

## Outliers

Analisando Idade

Vamos verificar valores estranhos.

Nossa coluna possui:

- 25 anos
- 35 anos
- 42 anos
- 150 anos
- -5 anos

Claramente existem problemas.

In [ ]:
df["Idade"].describe()

In [ ]:
# Criando limites

Q1 = df["Idade"].quantile(0.25)

Q3 = df["Idade"].quantile(0.75)

IQR = Q3 - Q1


limite_inferior = Q1 - 1.5 * IQR

limite_superior = Q3 + 1.5 * IQR


print(limite_inferior)
print(limite_superior)

In [ ]:
# Encontrando outliers

df[
    (df["Idade"] < limite_inferior) |
    (df["Idade"] > limite_superior)
]

Neste caso, 150 anos e -5 anos são claramente erros.
Vamos remover.

In [ ]:
df = df[
    (df["Idade"] >= 0) &
    (df["Idade"] <= 120)
]

### Analisando Vendas

In [ ]:
df["Venda_Total"].describe()

Existe uma venda de 25000.

Devemos remover?

Não necessariamente.

Pode ser:

- Compra corporativa
- Cliente especial
- Venda anual

O contexto do negócio sempre deve ser analisado.

## Normalização
Corrigir as cidades.

In [ ]:
df["Cidade"] = df["Cidade"].str.strip()

df["Cidade"] = df["Cidade"].str.title()

In [ ]:
# Conferir únicos
df["Cidade"].unique()

Às vezes existem abreviações ou erros específicos.

Exemplo:

BNU

deve virar

Blumenau

In [ ]:
df["Cidade"] = df["Cidade"].replace(
    "BNU",
    "Blumenau"
)

### Conversão de tipos

In [ ]:
df.dtypes

In [ ]:
df["Idade"] = pd.to_numeric(
    df["Idade"],
    errors="coerce" #  transforma valores inválidos em NaN
)

In [ ]:
df

## Antes e Depois

## Antes da limpeza:

❌ Idade vazia  
❌ Idade impossível  
❌ Cidade com vários formatos  
❌ Clientes duplicados  
❌ Venda vazia  


## Depois:

✅ Dados padronizados  
✅ Valores ausentes tratados  
✅ Duplicatas removidas  
✅ Dados prontos para análise

# Desafio

Crie uma nova base chamada "Funcionarios".

Ela deve possuir:

- Nome
- Idade
- Cidade


Inclua propositalmente:

- Valores vazios
- Cidades com letras diferentes
- Um registro duplicado


Depois:

1. Identifique valores ausentes.
2. Preencha os valores necessários.
3. Remova duplicatas.
4. Padronize as cidades.